fixtures:
  repositories:
    concat: https://github.com/puppetlabs/puppetlabs-concat.git
    ruby: https://github.com/evenup/evenup-ruby.git
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
  symlinks:
    backups: "#{source_dir}"

