fixtures:
  repositories:
    concat: git://github.com/ripienaar/puppet-concat.git
    ruby: git://github.com/evenup/evenup-ruby.git
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
  symlinks:
    backups: "#{source_dir}"

